language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t 9fevrier/travis-python-ta-lib-pandas .

script:
  - docker run --rm --name python-ta-lib-pandas -t 9fevrier/travis-python-ta-lib-pandas python3 -c 'import pandas'
  - docker run --rm --name python-ta-lib-pandas -t 9fevrier/travis-python-ta-lib-pandas python3 -c 'import talib'
